#!/usr/bin/env bash

set -xv 
source /etc/bash.bashrc
source /etc/profile

	cd /tmp
	rm -rf blur-miner 2>/dev/null
	git clone https://github.com/cogitocat/blur.git
	cd blur/blur-miner-xmrig-unofficial/
	mkdir bin
	cd bin
	# AOCC Changes
	source /opt/AMD/aocc-compiler-2.1.0/setenv_AOCC.sh
	export CC=/opt/AMD/aocc-compiler-2.1.0/bin/clang
	export CXX=/opt/AMD/aocc-compiler-2.1.0/bin/clang++
	cmake -WITH_OPENCL=OFF -DCMAKE_C_FLAGS="-O3 -march=native -funroll-loops -fomit-frame-pointer" ..
	#cmake -WITH_OPENCL=OFF ..
	make -j6
#	cmake -DCMAKE_C_COMPILER=/usr/bin/gcc ../xmrig-cuda
#	make -j6
#	cp ./libxmrig-cuda.so ../libxmrig-cuda.so

	mv ../bin /blur-miner
